version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: ./bot
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  admin_panel:
    build:
      context: ./admin_panel
    container_name: admin_panel
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./admin_panel:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
