version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db_shop
      POSTGRES_USER: stanislav
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    build:
      context: ./admin_panel
    container_name: admin_panel
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: db_shop
      POSTGRES_USER: stanislav
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./admin_panel:/app

  bot:
    build:
      context: ./bot
    container_name: telegram_bot
    command: bash entrypoint.sh
    environment:
      POSTGRES_DB: db_shop
      POSTGRES_USER: stanislav
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    volumes:
      - ./bot:/app

volumes:
  pgdata:
