version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bot_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - bot_network

  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: django_admin
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge